🌈 add feedback after mark as done a task
toti1212/todo-cli pull request #10
Opened 2019-07-15 14:26 UTC by brunocerecetto

Closes #8

2019-07-15 20:19 UTC, toti1212 commented
Hi @brunocerecetto! Good to see you here! Thanks for work on this! 🙌.
Looks good for me! Could you make one minor changes?

2019-07-15 20:28 UTC, toti1212 requested changes
Hi @brunocerecetto! Good to see you here! Thanks for work on this! 🙌.
Looks good for me! Could you make one minor change?

2019-07-15 20:28 UTC, toti1212 commented on src/commands/done.js
> +        // const dataTodo = await list('todo');
Could you remove these comments?

2019-07-15 20:28 UTC, toti1212 commented on src/utils/constants.js
> +  DONE_HAS_BEEN_MARKED: index =>
Rename the constants. Maybe to `DONE_ITEM_DONE` or `DONE_ITEM_MARKED`

2019-07-16 01:39 UTC, brunocerecetto commented
Done!

2019-07-16 03:11 UTC, toti1212 approved these changes

2019-07-16 03:23 UTC, merged